Issue107反馈内容
ITCraftDevelopmentTeam/XDbot2 pull request #122
Opened 2023-04-02 10:12 UTC by FZZkill

如果您看见了这个Pr，可以Close掉[https://github.com/This-is-XiaoDeng/XDbot2/issues/107](issue107)

2023-04-02 11:59 UTC, This-is-XiaoDeng requested changes
整体没啥问题，你看着改改（）

2023-04-02 11:59 UTC, This-is-XiaoDeng commented on bot.py
> +        "Always use `nb run` to start the bot instead of manually running!"
其实这个warning要看不顺眼可以删掉（）

2023-04-02 11:59 UTC, This-is-XiaoDeng commented on src/plugins/Core/__init__.py
> +    r"(.*)\.ro\.(.*)",
？

2023-04-02 11:59 UTC, This-is-XiaoDeng commented on src/plugins/Core/__init__.py
> +    open("data/init.json", "w", encoding="utf-8"),
？

2023-04-02 11:59 UTC, This-is-XiaoDeng commented on src/plugins/Core/getHelp.py
> +        lines = plugin_file[start: plugin_file.find("# [HELPEND]", start)]
？

2023-04-02 11:59 UTC, This-is-XiaoDeng commented on src/plugins/Core/lang/zh_fzz.json
> +  "cave.help": {
我在想为什么lang会出现这个东西

2023-04-02 11:59 UTC, This-is-XiaoDeng commented on src/plugins/Core/lang/zh_hans.json
>    "status.ram": "内存：",
亲，是不是乱码了

2023-04-02 11:59 UTC, This-is-XiaoDeng commented on src/plugins/Core/lang/zh_hans.json
> +  "cave.help": {
？这个是帮助文本啊不需要本地化

2023-04-02 11:59 UTC, This-is-XiaoDeng commented on src/plugins/Core/plugins/_smart_reply.py
> +        "user_id": user_id,
？

2023-04-02 11:59 UTC, This-is-XiaoDeng commented on src/plugins/Core/plugins/cave.py
> -commandHelp = {
？

2023-04-02 11:59 UTC, This-is-XiaoDeng commented on src/plugins/Core/plugins/cave.py
> +                "time": time.time(),
？

2023-04-02 11:59 UTC, This-is-XiaoDeng commented on src/plugins/Core/plugins/etm/achievement.py
> +def unlock(name, user_id):
6，这要改的多了

2023-04-02 11:59 UTC, This-is-XiaoDeng commented on src/plugins/Core/plugins/etm/item_basic_data.py
> +    "can_use": False,
~~你下次能不能不要写这么迷惑的操作~~

2023-04-02 11:59 UTC, This-is-XiaoDeng commented on src/plugins/Core/lang/zh_hans.json
你看看这个文件它是不是乱码了

2023-04-02 11:59 UTC, This-is-XiaoDeng commented on src/plugins/Core/plugins/messenger.py
这个发件部分到时候直接用`_messenger.py`得了（我自己改）

2023-04-02 11:59 UTC, This-is-XiaoDeng commented on src/plugins/Core/plugins/random_number.py
> +run_sandbox = lua.eval("run_sandbox")
你lua那边那个函数好像不叫这个吧？

2023-04-02 11:59 UTC, This-is-XiaoDeng commented on src/plugins/Core/plugins/random_number.py
> +            result = run_sandbox(0, 1)
为什么要用lua（？

下同

2023-04-02 11:59 UTC, This-is-XiaoDeng commented on src/plugins/Core/plugins/su_log.py
> +                "s": time.strftime("%S", _log_time),
？

2023-04-02 12:13 UTC, This-is-XiaoDeng commented
推荐解决方案：先用autopep8格式化一遍迷惑操作就少点了

```bash
find /path/to/XDbot2 -name "*.py" python -m autopep8 -a -i
```

然后`zh_hans.json`的编码检查下或者重写一下，cave的commandHelp变量放回去，lua那个函数改了

其他的可以不改，然后Request我审查

2023-04-07 04:15 UTC, XieXiLin3 commented
现有合并冲突。
![合并冲突](https://user-images.githubusercontent.com/55585872/230539631-4e1fe566-405f-4949-824b-0f79b72766b9.png)

2023-04-29 01:45 UTC, This-is-XiaoDeng commented
![图片](https://user-images.githubusercontent.com/104149371/235277883-30cccf24-b5b0-4bc2-a6ef-f80b4bcaee65.png)
现有合并冲突

2023-04-29 01:46 UTC, This-is-XiaoDeng commented
感谢，到那时合并冲突太多先关了（）

2023-04-29 01:46 UTC, closed without merging

2023-04-29 01:50 UTC, montmorill commented
草