一些关于quick_math的彩蛋（？
ITCraftDevelopmentTeam/XDbot2 pull request #291
Opened 2023-06-28 07:52 UTC by montmorill

2023-06-28 07:54 UTC, This-is-XiaoDeng commented
这没合并冲突也是个奇迹（

2023-06-28 07:56 UTC, This-is-XiaoDeng requested changes

2023-06-28 07:56 UTC, This-is-XiaoDeng commented on src/plugins/Core/plugins/quick_math.py
> -    # 彩蛋
9？

2023-06-28 07:56 UTC, This-is-XiaoDeng commented
除了加彩蛋其他的感觉有点奇怪

2023-06-28 07:57 UTC, montmorill commented on src/plugins/Core/plugins/quick_math.py
> -    # 彩蛋
?

2023-06-28 07:58 UTC, This-is-XiaoDeng reviewed
寄，看不懂你写的正则（

2023-06-28 07:58 UTC, This-is-XiaoDeng commented
好像看懂了（

2023-06-28 07:59 UTC, montmorill commented
乐

2023-07-01 01:41 UTC, This-is-XiaoDeng reviewed
太坏了，准备单独抄一部分过去（

感谢啦～

2023-07-01 01:41 UTC, This-is-XiaoDeng approved these changes

2023-07-01 01:41 UTC, merged